name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Google Cloud Credentials
        run: echo "${{ secrets.GOOGLE_CLOUD_JSON_KEY }}" > google-cloud-credentials.json

      - name: Run Streamlit App
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=google-cloud-credentials.json
          streamlit run app.py
